### ISSUE TITLE
org-hide-emphasis-markers and org-appear-mode

### ISSUE THREAD

**Issue by keevee09** [jdtsmith/shakespeare.org#1]
I have an OK system - 2010 era i7 with 12GB DDR3 memory. I am running Doom-Emacs with emacs v28.2 and the following settings in my config.el file:

`(setq org-hide-emphasis-markers t)`
`(add-hook! org-mode :append #'org-appear-mode)`

There is a sizeable freeze of a few seconds whenever I move the cursor over an emphasized word -- e.g. *this* or **that**.
Commenting out the org-appear-mode line in my config.el improves matters but it is still a bit unwieldy on my system. I would be tempted to split the file into individual plays if I was to use it.

Thanks for the interesting test!

EDIT:
Ok, unfolding just one section at a time improves performance but it is still sluggish. I would still look at splitting the file up if I was to work on it.

**Comment by jdtsmith** [comment]
Yeah, I hide emphasis and use org-appear too, and don't have much of a problem.  My old laptop is a core i7 from 2015.  If you set `org-appear-trigger` to `'on-change` it will not have to do so much revealing.

You might consider opening an issue with `org-appear` to see if they could optimize (pointing to this file).

**Comment by keevee09** [comment]
Thanks for the tip. I'll try it and perhaps open an issue with org-appear.
Htop shows just one thread running a single cpu when I hover over an
emphasised word.

**Comment by jdtsmith** [comment]
Emacs never runs more than a single thread on one CPU, sadly. So single core speed is pretty important.
